
version: '3.7'

services:
  apps:
    build: 
      context: .
    command: sh -c "bundle exec jekyll serve"
    expose:
      - 5000
    volumes:
      - .:/apps
  
  nginx:
    build: ./nginx
    volumes:
      - .:/nginx/etc/nginx/conf.d/
    ports:
      - 4000:80
    depends_on:
      - apps